# Generated by Django 2.1.5 on 2019-02-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
